version: '3'
services:
  web:
    image: nginx:1.19.7
    ports:
      - "80:80"
    links:
      - php
    volumes:
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
      - ./2048:/usr/2048/
    networks:
      - app-network
  php:
    image: php:7.4-fpm
    volumes:
      - ./2048:/usr/2048/
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - app-network
networks:
  app-network:
    driver: bridge